### ISSUE TITLE
Attribute Listing

### ISSUE THREAD

**Issue by djacobsmeyer** [djacobsmeyer/LC_Meetup_Connect#2]
In the new 'Model Attribute List' wiki page, lets make a list of all the attributes we want a given Meetup object and User object to have. I've started it off with a few for example. Come up with as many useful attributes we would want to record about each of the two models. There is no right or wrong answer, just what we choose to implement.

**Comment by SashaWH** [comment]
Attached are the attributes by categories, i.e. music, hobbies, sports, etc.
[Attributes.docx](https://github.com/djacobsmeyer/LC_Meetup_Connect/files/196224/Attributes.docx)
